In [72]:
# Install Kaggle API
!pip install kaggle
import kaggle

Requirement already satisfied: kaggle in /opt/anaconda3/lib/python3.12/site-packages (1.7.4.5)
Requirement already satisfied: bleach in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (3.3.2)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (3.7)
Requirement already satisfied: protobuf in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (4.25.3)
Requirement already satisfied: python-dateutil>=2.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (75.1.0)
Requirement already satisfied: six>=1.10 in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (1.16.0)
Requirement already satisfied: text-unidecode in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (4.66.5)
Requirement already satisfied: urllib3>=1.15.1 in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2.2.3)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (0.5.1)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from bleach->kaggle) (24.1)

In [73]:
# Download Kaggle dataset
!kaggle datasets download ajaxianazarenka/premier-league -f PremierLeague.csv

Dataset URL: https://www.kaggle.com/datasets/ajaxianazarenka/premier-league
License(s): MIT
Downloading PremierLeague.csv to /Users/ericgalbarn/Documents/sample data file for analysis/epl_players_stats
  0%|                                               | 0.00/1.78M [00:00<?, ?B/s]
100%|██████████████████████████████████████| 1.78M/1.78M [00:00<00:00, 1.25GB/s]

In [74]:
#Extract zipfile (Not used in this case as it's unzipped already)

# import zipfile
# zip_ref = zipfile.ZipFile('dataset.zip')
# zip_ref.extractall() extract file to directory
# zip_ref.close() # close file

In [2]:
# Read data from the file and handle null values
import pandas as pd
df = pd.read_csv('raw_data_epl_stats.csv')
df.head(10)
# df['MarketAvgDraw'].unique()

,MatchID,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,...,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
5,1993-1994_Newcastle_Tottenham,1993-1994,1,1993-08-14,NaN,Newcastle,Tottenham,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
6,1993-1994_Oldham_Ipswich,1993-1994,1,1993-08-14,NaN,Oldham,Ipswich,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
7,1993-1994_Sheffield United_Swindon,1993-1994,1,1993-08-14,NaN,Sheffield United,Swindon,3,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
8,1993-1994_Southampton_Everton,1993-1994,1,1993-08-14,NaN,Southampton,Everton,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
9,1993-1994_West Ham_Wimbledon,1993-1994,1,1993-08-14,NaN,West Ham,Wimbledon,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3

In [3]:
# Rename column names to standardize them into lower case and replace space with underscore (Can't replace all as there're too many columns)

#Below is the manual rename (Bad practice)
# df.rename(columns={'MatchID': 'match_id', 'Season': 'season', 'MatchWeek': 'match_week', 'Date': 'date', 'Time': 'time', 'HomeTeam': 'home_team', 'AwayTeam': 'away_team', 'FullTimeHomeTeamGoals': 'fulltime_home_team_goals', 'FullTimeAwayTeamGoals': 'fulltime_away_team_goals', 'FullTimeResult': 'fulltime_result'})

# Below is automatic rename (Best Practice)
df.columns = df.columns.str.lower()

# In case within the string, there's a space for now reason, we can standardize by replacing them with '_'
# df.columns = df.columns.str.replace('','_')

# Show the current column of the data file after change
df.columns

Index(['matchid', 'season', 'matchweek', 'date', 'time', 'hometeam',
       'awayteam', 'fulltimehometeamgoals', 'fulltimeawayteamgoals',
       'fulltimeresult', 'halftimehometeamgoals', 'halftimeawayteamgoals',
       'halftimeresult', 'referee', 'hometeamshots', 'awayteamshots',
       'hometeamshotsontarget', 'awayteamshotsontarget', 'hometeamcorners',
       'awayteamcorners', 'hometeamfouls', 'awayteamfouls',
       'hometeamyellowcards', 'awayteamyellowcards', 'hometeamredcards',
       'awayteamredcards', 'b365hometeam', 'b365draw', 'b365awayteam',
       'b365over2.5goals', 'b365under2.5goals', 'marketmaxhometeam',
       'marketmaxdraw', 'marketmaxawayteam', 'marketavghometeam',
       'marketavgdraw', 'marketavgawayteam', 'marketmaxover2.5goals',
       'marketmaxunder2.5goals', 'marketavgover2.5goals',
       'marketavgunder2.5goals', 'hometeampoints', 'awayteampoints'],
      dtype='object')

In [4]:
# Reread the updated dataset
df.head(10)

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketmaxawayteam,marketavghometeam,marketavgdraw,marketavgawayteam,marketmaxover2.5goals,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
5,1993-1994_Newcastle_Tottenham,1993-1994,1,1993-08-14,NaN,Newcastle,Tottenham,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
6,1993-1994_Oldham_Ipswich,1993-1994,1,1993-08-14,NaN,Oldham,Ipswich,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
7,1993-1994_Sheffield United_Swindon,1993-1994,1,1993-08-14,NaN,Sheffield United,Swindon,3,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
8,1993-1994_Southampton_Everton,1993-1994,1,1993-08-14,NaN,Southampton,Everton,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
9,1993-1994_West Ham_Wimbledon,1993-1994,1,1993-08-14,NaN,West Ham,Wimbledon,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3

In [5]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketmaxawayteam,marketavghometeam,marketavgdraw,marketavgawayteam,marketmaxover2.5goals,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,3.00,2.33,3.59,2.94,1.77,2.18,1.74,2.11,3,0
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,3.83,2.01,3.59,3.70,1.82,2.13,1.77,2.06,3,0
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,2.50,2.63,3.82,2.46,1.48,2.75,1.45,2.70,3,0
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,3.36,2.27,3.32,3.26,2.05,1.89,1.99,1.83,3,0
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,5.80,1.55,4.51,5.49,1.55,2.60,1.51,2.52,3,0

In [6]:
# Derive new insights
# Shooting Accuracy for Home Team
import numpy as np

# Fill NaN values in relevant columns with 0
df['hometeamshots'].fillna(0, inplace=True)
df['hometeamshotsontarget'].fillna(0, inplace=True)

# Convert relevant columns to NumPy arrays for faster calculations
hometeamshots = df['hometeamshots'].to_numpy()
hometeamshotsontarget = df['hometeamshotsontarget'].to_numpy()

# Calculate Shooting Accuracy using NumPy and handle division by zero
hometeam_shooting_accuracy = np.zeros_like(hometeamshots, dtype=float)  # Initialize array with zeros

# Only calculate where shots are greater than zero
valid_indices = hometeamshots > 0
hometeam_shooting_accuracy[valid_indices] = (hometeamshotsontarget[valid_indices] / hometeamshots[valid_indices]) * 100 

# Adding the calculated accuracy back to the DataFrame
df['hometeam_shooting_accuracy'] = hometeam_shooting_accuracy

In [7]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketavghometeam,marketavgdraw,marketavgawayteam,marketmaxover2.5goals,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3,0.000000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0.000000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3,0.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,2.33,3.59,2.94,1.77,2.18,1.74,2.11,3,0,33.333333
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,2.01,3.59,3.70,1.82,2.13,1.77,2.06,3,0,33.333333
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,2.63,3.82,2.46,1.48,2.75,1.45,2.70,3,0,48.000000
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,2.27,3.32,3.26,2.05,1.89,1.99,1.83,3,0,71.428571
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,1.55,4.51,5.49,1.55,2.60,1.51,2.52,3,0,41.666667

In [8]:
# Shooting Accuracy for Away Team
import numpy as np

# Fill NaN values in relevant columns with 0
df['awayteamshots'].fillna(0, inplace=True)
df['awayteamshotsontarget'].fillna(0, inplace=True)

# Convert Away Team shots column to NumPy arrays for faster calculations
awayteamshots = df['awayteamshots'].to_numpy()
awayteamshotsontarget = df['awayteamshotsontarget'].to_numpy()

# Calculate Shooting Accuracy using NumPy and handle division by zero
awayteam_shooting_accuracy = np.zeros_like(awayteamshots, dtype=float)  # Initialize array with zeros

# Only calculate where shots are greater than zero
valid_indices_awayteam = awayteamshots > 0
awayteam_shooting_accuracy[valid_indices_awayteam] = (awayteamshotsontarget[valid_indices_awayteam] / awayteamshots[valid_indices_awayteam]) * 100 

# Adding the calculated accuracy back to the DataFrame
df['awayteam_shooting_accuracy'] = awayteam_shooting_accuracy

In [9]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketavgdraw,marketavgawayteam,marketmaxover2.5goals,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,0,3,0.000000,0.000000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0.000000,0.000000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,0,3,0.000000,0.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0.000000,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,3.59,2.94,1.77,2.18,1.74,2.11,3,0,33.333333,10.000000
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,3.59,3.70,1.82,2.13,1.77,2.06,3,0,33.333333,35.714286
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,3.82,2.46,1.48,2.75,1.45,2.70,3,0,48.000000,27.777778
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,3.32,3.26,2.05,1.89,1.99,1.83,3,0,71.428571,25.000000
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,4.51,5.49,1.55,2.60,1.51,2.52,3,0,41.666667,25.000000

In [10]:
# Home/Away Goal Difference
import numpy as np

# Fill NaN values in goals columns with 0
df['fulltimehometeamgoals'].fillna(0, inplace=True)
df['fulltimeawayteamgoals'].fillna(0, inplace=True)

# Convert Full time home/away team goals column to NumPy arrays for faster calculations
fulltimehometeamgoals = df['fulltimehometeamgoals'].to_numpy()
fulltimeawayteamgoals = df['fulltimeawayteamgoals'].to_numpy()

# Home Goal Difference Formula
df['goal_difference_home'] = fulltimehometeamgoals - fulltimeawayteamgoals

In [11]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketavgawayteam,marketmaxover2.5goals,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,0,3,0.000000,0.000000,-3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,3,0,0.000000,0.000000,3
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,0,3,0.000000,0.000000,-1
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,3,0,0.000000,0.000000,2
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,1,1,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,2.94,1.77,2.18,1.74,2.11,3,0,33.333333,10.000000,2
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,3.70,1.82,2.13,1.77,2.06,3,0,33.333333,35.714286,1
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,2.46,1.48,2.75,1.45,2.70,3,0,48.000000,27.777778,1
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,3.26,2.05,1.89,1.99,1.83,3,0,71.428571,25.000000,2
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,5.49,1.55,2.60,1.51,2.52,3,0,41.666667,25.000000,2

In [12]:
# Away Goal Difference Formula
df['goal_difference_away'] = fulltimeawayteamgoals - fulltimehometeamgoals

In [13]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketmaxover2.5goals,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,0,3,0.000000,0.000000,-3,3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,3,0,0.000000,0.000000,3,-3
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,0,3,0.000000,0.000000,-1,1
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,3,0,0.000000,0.000000,2,-2
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,1,1,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,1.77,2.18,1.74,2.11,3,0,33.333333,10.000000,2,-2
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,1.82,2.13,1.77,2.06,3,0,33.333333,35.714286,1,-1
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,1.48,2.75,1.45,2.70,3,0,48.000000,27.777778,1,-1
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,2.05,1.89,1.99,1.83,3,0,71.428571,25.000000,2,-2
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,1.55,2.60,1.51,2.52,3,0,41.666667,25.000000,2,-2

In [14]:
import numpy as np

# Calculate Shots on Target Ratio for Home Team
home_shots_on_target_ratio = np.zeros_like(df['hometeamshots'], dtype=float)  # Initialize with zeros
valid_home_indices = df['hometeamshots'] > 0  # Check for valid total shots (non-zero)

# Calculate the ratio where total shots are valid
home_shots_on_target_ratio[valid_home_indices] = (df['hometeamshotsontarget'][valid_home_indices] / df['hometeamshots'][valid_home_indices])

df['home_shots_on_target_ratio'] = home_shots_on_target_ratio

In [15]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketmaxunder2.5goals,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,0,3,0.000000,0.000000,-3,3,0.000000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,3,0,0.000000,0.000000,3,-3,0.000000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,0,3,0.000000,0.000000,-1,1,0.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,3,0,0.000000,0.000000,2,-2,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,1,1,0.000000,0.000000,0,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,2.18,1.74,2.11,3,0,33.333333,10.000000,2,-2,0.333333
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,2.13,1.77,2.06,3,0,33.333333,35.714286,1,-1,0.333333
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,2.75,1.45,2.70,3,0,48.000000,27.777778,1,-1,0.480000
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,1.89,1.99,1.83,3,0,71.428571,25.000000,2,-2,0.714286
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,2.60,1.51,2.52,3,0,41.666667,25.000000,2,-2,0.416667

In [16]:
import numpy as np

# Calculate Shots on Target Ratio for Away Team
away_shots_on_target_ratio = np.zeros_like(df['awayteamshots'], dtype=float)  # Initialize with zeros
valid_indices_awayteam = df['awayteamshots'] > 0  # Check for valid total shots (non-zero)

# Calculate the ratio where total shots are valid
away_shots_on_target_ratio[valid_indices_awayteam] = (df['awayteamshotsontarget'][valid_indices_awayteam] / df['awayteamshots'][valid_indices_awayteam])

df['away_shots_on_target_ratio'] = away_shots_on_target_ratio

In [17]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketavgover2.5goals,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,0,3,0.000000,0.000000,-3,3,0.000000,0.000000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,3,0,0.000000,0.000000,3,-3,0.000000,0.000000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,0,3,0.000000,0.000000,-1,1,0.000000,0.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,3,0,0.000000,0.000000,2,-2,0.000000,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,1,1,0.000000,0.000000,0,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,1.74,2.11,3,0,33.333333,10.000000,2,-2,0.333333,0.100000
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,1.77,2.06,3,0,33.333333,35.714286,1,-1,0.333333,0.357143
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,1.45,2.70,3,0,48.000000,27.777778,1,-1,0.480000,0.277778
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,1.99,1.83,3,0,71.428571,25.000000,2,-2,0.714286,0.250000
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,1.51,2.52,3,0,41.666667,25.000000,2,-2,0.416667,0.250000

In [18]:
# Calculate Home Team Performance Index (HPI)
df['home_performance_index'] = (fulltimehometeamgoals + home_shots_on_target_ratio) / 2

In [19]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,marketavgunder2.5goals,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio,home_performance_index
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,0,3,0.000000,0.000000,-3,3,0.000000,0.000000,0.000000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,3,0,0.000000,0.000000,3,-3,0.000000,0.000000,2.000000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,0,3,0.000000,0.000000,-1,1,0.000000,0.000000,0.500000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,3,0,0.000000,0.000000,2,-2,0.000000,0.000000,1.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,1,1,0.000000,0.000000,0,0,0.000000,0.000000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,2.11,3,0,33.333333,10.000000,2,-2,0.333333,0.100000,1.166667
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,2.06,3,0,33.333333,35.714286,1,-1,0.333333,0.357143,0.666667
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,2.70,3,0,48.000000,27.777778,1,-1,0.480000,0.277778,1.740000
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,1.83,3,0,71.428571,25.000000,2,-2,0.714286,0.250000,2.357143
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,2.52,3,0,41.666667,25.000000,2,-2,0.416667,0.250000,1.708333

In [20]:
# Calculate Away Team Performance Index (HPI)
df['away_performance_index'] = (fulltimeawayteamgoals + away_shots_on_target_ratio) / 2

In [21]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio,home_performance_index,away_performance_index
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,0,3,0.000000,0.000000,-3,3,0.000000,0.000000,0.000000,1.500000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,3,0,0.000000,0.000000,3,-3,0.000000,0.000000,2.000000,0.500000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,0,3,0.000000,0.000000,-1,1,0.000000,0.000000,0.500000,1.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,3,0,0.000000,0.000000,2,-2,0.000000,0.000000,1.000000,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,1,1,0.000000,0.000000,0,0,0.000000,0.000000,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,3,0,33.333333,10.000000,2,-2,0.333333,0.100000,1.166667,0.050000
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,3,0,33.333333,35.714286,1,-1,0.333333,0.357143,0.666667,0.178571
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,3,0,48.000000,27.777778,1,-1,0.480000,0.277778,1.740000,1.138889
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,3,0,71.428571,25.000000,2,-2,0.714286,0.250000,2.357143,1.125000
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,3,0,41.666667,25.000000,2,-2,0.416667,0.250000,1.708333,0.625000

In [22]:
# Check for the datatypes of all the existing columns in the CSV file
df.dtypes

matchid                        object
season                         object
matchweek                       int64
date                           object
time                           object
hometeam                       object
awayteam                       object
fulltimehometeamgoals           int64
fulltimeawayteamgoals           int64
fulltimeresult                 object
halftimehometeamgoals         float64
halftimeawayteamgoals         float64
halftimeresult                 object
referee                        object
hometeamshots                 float64
awayteamshots                 float64
hometeamshotsontarget         float64
awayteamshotsontarget         float64
hometeamcorners               float64
awayteamcorners               float64
hometeamfouls                 float64
awayteamfouls                 float64
hometeamyellowcards           float64
awayteamyellowcards           float64
hometeamredcards              float64
awayteamredcards              float64
b365hometeam                  float64
b365draw                      float64
b365awayteam                  float64
b365over2.5goals              float64
b365under2.5goals             float64
marketmaxhometeam             float64
marketmaxdraw                 float64
marketmaxawayteam             float64
marketavghometeam             float64
marketavgdraw                 float64
marketavgawayteam             float64
marketmaxover2.5goals         float64
marketmaxunder2.5goals        float64
marketavgover2.5goals         float64
marketavgunder2.5goals        float64
hometeampoints                  int64
awayteampoints                  int64
hometeam_shooting_accuracy    float64
awayteam_shooting_accuracy    float64
goal_difference_home            int64
goal_difference_away            int64
home_shots_on_target_ratio    float64
away_shots_on_target_ratio    float64
home_performance_index        float64
away_performance_index        float64
dtype: object

In [23]:
# Convert order date from object type to the accurate datastype
df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d")

In [24]:
df.dtypes

matchid                               object
season                                object
matchweek                              int64
date                          datetime64[ns]
time                                  object
hometeam                              object
awayteam                              object
fulltimehometeamgoals                  int64
fulltimeawayteamgoals                  int64
fulltimeresult                        object
halftimehometeamgoals                float64
halftimeawayteamgoals                float64
halftimeresult                        object
referee                               object
hometeamshots                        float64
awayteamshots                        float64
hometeamshotsontarget                float64
awayteamshotsontarget                float64
hometeamcorners                      float64
awayteamcorners                      float64
hometeamfouls                        float64
awayteamfouls                        float64
hometeamyellowcards                  float64
awayteamyellowcards                  float64
hometeamredcards                     float64
awayteamredcards                     float64
b365hometeam                         float64
b365draw                             float64
b365awayteam                         float64
b365over2.5goals                     float64
b365under2.5goals                    float64
marketmaxhometeam                    float64
marketmaxdraw                        float64
marketmaxawayteam                    float64
marketavghometeam                    float64
marketavgdraw                        float64
marketavgawayteam                    float64
marketmaxover2.5goals                float64
marketmaxunder2.5goals               float64
marketavgover2.5goals                float64
marketavgunder2.5goals               float64
hometeampoints                         int64
awayteampoints                         int64
hometeam_shooting_accuracy           float64
awayteam_shooting_accuracy           float64
goal_difference_home                   int64
goal_difference_away                   int64
home_shots_on_target_ratio           float64
away_shots_on_target_ratio           float64
home_performance_index               float64
away_performance_index               float64
dtype: object

In [25]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio,home_performance_index,away_performance_index
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,0,3,0.000000,0.000000,-3,3,0.000000,0.000000,0.000000,1.500000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,3,0,0.000000,0.000000,3,-3,0.000000,0.000000,2.000000,0.500000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,0,3,0.000000,0.000000,-1,1,0.000000,0.000000,0.500000,1.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,3,0,0.000000,0.000000,2,-2,0.000000,0.000000,1.000000,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,1,1,0.000000,0.000000,0,0,0.000000,0.000000,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00,Leicester,Ipswich,2,0,H,...,3,0,33.333333,10.000000,2,-2,0.333333,0.100000,1.166667,0.050000
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30,Arsenal,Newcastle,1,0,H,...,3,0,33.333333,35.714286,1,-1,0.333333,0.357143,0.666667,0.178571
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00,Brighton,Liverpool,3,2,H,...,3,0,48.000000,27.777778,1,-1,0.480000,0.277778,1.740000,1.138889
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00,Crystal Palace,Wolves,4,2,H,...,3,0,71.428571,25.000000,2,-2,0.714286,0.250000,2.357143,1.125000
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00,Man City,Bournemouth,3,1,H,...,3,0,41.666667,25.000000,2,-2,0.416667,0.250000,1.708333,0.625000

In [26]:
# Convert time column from object type to time format
import pandas as pd
df['time'] = pd.to_datetime(df['time'], format="%H:%M").dt.time
# errors='coerce' turns any parsing errors into NaT (Not a Time), similar to handling NaN values.

In [27]:
df.dtypes

matchid                               object
season                                object
matchweek                              int64
date                          datetime64[ns]
time                                  object
hometeam                              object
awayteam                              object
fulltimehometeamgoals                  int64
fulltimeawayteamgoals                  int64
fulltimeresult                        object
halftimehometeamgoals                float64
halftimeawayteamgoals                float64
halftimeresult                        object
referee                               object
hometeamshots                        float64
awayteamshots                        float64
hometeamshotsontarget                float64
awayteamshotsontarget                float64
hometeamcorners                      float64
awayteamcorners                      float64
hometeamfouls                        float64
awayteamfouls                        float64
hometeamyellowcards                  float64
awayteamyellowcards                  float64
hometeamredcards                     float64
awayteamredcards                     float64
b365hometeam                         float64
b365draw                             float64
b365awayteam                         float64
b365over2.5goals                     float64
b365under2.5goals                    float64
marketmaxhometeam                    float64
marketmaxdraw                        float64
marketmaxawayteam                    float64
marketavghometeam                    float64
marketavgdraw                        float64
marketavgawayteam                    float64
marketmaxover2.5goals                float64
marketmaxunder2.5goals               float64
marketavgover2.5goals                float64
marketavgunder2.5goals               float64
hometeampoints                         int64
awayteampoints                         int64
hometeam_shooting_accuracy           float64
awayteam_shooting_accuracy           float64
goal_difference_home                   int64
goal_difference_away                   int64
home_shots_on_target_ratio           float64
away_shots_on_target_ratio           float64
home_performance_index               float64
away_performance_index               float64
dtype: object

In [28]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio,home_performance_index,away_performance_index
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaT,Arsenal,Coventry,0,3,A,...,0,3,0.000000,0.000000,-3,3,0.000000,0.000000,0.000000,1.500000
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaT,Aston Villa,QPR,4,1,H,...,3,0,0.000000,0.000000,3,-3,0.000000,0.000000,2.000000,0.500000
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaT,Chelsea,Blackburn,1,2,A,...,0,3,0.000000,0.000000,-1,1,0.000000,0.000000,0.500000,1.000000
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaT,Liverpool,Sheffield Weds,2,0,H,...,3,0,0.000000,0.000000,2,-2,0.000000,0.000000,1.000000,0.000000
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaT,Man City,Leeds,1,1,D,...,1,1,0.000000,0.000000,0,0,0.000000,0.000000,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12145,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00:00,Leicester,Ipswich,2,0,H,...,3,0,33.333333,10.000000,2,-2,0.333333,0.100000,1.166667,0.050000
12146,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30:00,Arsenal,Newcastle,1,0,H,...,3,0,33.333333,35.714286,1,-1,0.333333,0.357143,0.666667,0.178571
12147,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00:00,Brighton,Liverpool,3,2,H,...,3,0,48.000000,27.777778,1,-1,0.480000,0.277778,1.740000,1.138889
12148,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00:00,Crystal Palace,Wolves,4,2,H,...,3,0,71.428571,25.000000,2,-2,0.714286,0.250000,2.357143,1.125000
12149,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00:00,Man City,Bournemouth,3,1,H,...,3,0,41.666667,25.000000,2,-2,0.416667,0.250000,1.708333,0.625000

In [29]:
df.columns

Index(['matchid', 'season', 'matchweek', 'date', 'time', 'hometeam',
       'awayteam', 'fulltimehometeamgoals', 'fulltimeawayteamgoals',
       'fulltimeresult', 'halftimehometeamgoals', 'halftimeawayteamgoals',
       'halftimeresult', 'referee', 'hometeamshots', 'awayteamshots',
       'hometeamshotsontarget', 'awayteamshotsontarget', 'hometeamcorners',
       'awayteamcorners', 'hometeamfouls', 'awayteamfouls',
       'hometeamyellowcards', 'awayteamyellowcards', 'hometeamredcards',
       'awayteamredcards', 'b365hometeam', 'b365draw', 'b365awayteam',
       'b365over2.5goals', 'b365under2.5goals', 'marketmaxhometeam',
       'marketmaxdraw', 'marketmaxawayteam', 'marketavghometeam',
       'marketavgdraw', 'marketavgawayteam', 'marketmaxover2.5goals',
       'marketmaxunder2.5goals', 'marketavgover2.5goals',
       'marketavgunder2.5goals', 'hometeampoints', 'awayteampoints',
       'hometeam_shooting_accuracy', 'awayteam_shooting_accuracy',
       'goal_difference_home', 'goal_difference_away',
       'home_shots_on_target_ratio', 'away_shots_on_target_ratio',
       'home_performance_index', 'away_performance_index'],
      dtype='object')

In [34]:
# Generate descriptive statistics of EPL Players
df.describe()

,matchweek,fulltimehometeamgoals,fulltimeawayteamgoals,halftimehometeamgoals,halftimeawayteamgoals,hometeamshots,awayteamshots,hometeamshotsontarget,awayteamshotsontarget,hometeamcorners,...,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio,home_performance_index,away_performance_index
count,12150.000000,12150.000000,12150.000000,11390.000000,11390.000000,12150.000000,12150.000000,12150.000000,12150.000000,9490.000000,...,12150.000000,12150.000000,12150.000000,12150.000000,12150.00000,12150.00000,12150.000000,12150.000000,12150.000000,12150.000000
mean,18.977119,1.533169,1.164609,0.691747,0.511765,10.630700,8.436626,4.672099,3.667078,6.036986,...,1.627984,1.117613,34.550876,34.377491,0.36856,-0.36856,0.345509,0.343775,0.939339,0.754192
std,10.964596,1.309410,1.147913,0.840452,0.731605,7.349242,6.098005,3.802101,3.110688,3.108771,...,1.313376,1.262975,24.249950,25.108735,1.79599,1.79599,0.242500,0.251087,0.687398,0.611224
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,-9.00000,-9.00000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,1.000000,0.000000,0.000000,0.000000,6.000000,4.000000,1.000000,1.000000,4.000000,...,0.000000,0.000000,14.285714,12.500000,-1.00000,-1.00000,0.142857,0.125000,0.500000,0.227273
50%,19.000000,1.000000,1.000000,0.000000,0.000000,11.000000,9.000000,4.000000,3.000000,6.000000,...,1.000000,1.000000,37.500000,36.363636,0.00000,0.00000,0.375000,0.363636,0.781250,0.666667
75%,28.000000,2.000000,2.000000,1.000000,1.000000,16.000000,13.000000,7.000000,6.000000,8.000000,...,3.000000,3.000000,52.941176,52.941176,1.00000,1.00000,0.529412,0.529412,1.291667,1.166667
max,41.000000,9.000000,9.000000,5.000000,5.000000,43.000000,37.000000,24.000000,20.000000,20.000000,...,3.000000,3.000000,200.000000,266.666667,9.00000,9.00000,2.000000,2.666667,4.815789,4.800000

In [32]:
# Reset the index
df.reset_index(drop=True, inplace=True)

# Change the index to start from 1
df.index += 1

In [35]:
df

,matchid,season,matchweek,date,time,hometeam,awayteam,fulltimehometeamgoals,fulltimeawayteamgoals,fulltimeresult,...,hometeampoints,awayteampoints,hometeam_shooting_accuracy,awayteam_shooting_accuracy,goal_difference_home,goal_difference_away,home_shots_on_target_ratio,away_shots_on_target_ratio,home_performance_index,away_performance_index
1,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaT,Arsenal,Coventry,0,3,A,...,0,3,0.000000,0.000000,-3,3,0.000000,0.000000,0.000000,1.500000
2,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaT,Aston Villa,QPR,4,1,H,...,3,0,0.000000,0.000000,3,-3,0.000000,0.000000,2.000000,0.500000
3,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaT,Chelsea,Blackburn,1,2,A,...,0,3,0.000000,0.000000,-1,1,0.000000,0.000000,0.500000,1.000000
4,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaT,Liverpool,Sheffield Weds,2,0,H,...,3,0,0.000000,0.000000,2,-2,0.000000,0.000000,1.000000,0.000000
5,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaT,Man City,Leeds,1,1,D,...,1,1,0.000000,0.000000,0,0,0.000000,0.000000,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12146,2024-2025_Leicester_Ipswich,2024-2025,25,2025-05-18,15:00:00,Leicester,Ipswich,2,0,H,...,3,0,33.333333,10.000000,2,-2,0.333333,0.100000,1.166667,0.050000
12147,2024-2025_Arsenal_Newcastle,2024-2025,25,2025-05-18,16:30:00,Arsenal,Newcastle,1,0,H,...,3,0,33.333333,35.714286,1,-1,0.333333,0.357143,0.666667,0.178571
12148,2024-2025_Brighton_Liverpool,2024-2025,25,2025-05-19,20:00:00,Brighton,Liverpool,3,2,H,...,3,0,48.000000,27.777778,1,-1,0.480000,0.277778,1.740000,1.138889
12149,2024-2025_Crystal Palace_Wolves,2024-2025,25,2025-05-20,20:00:00,Crystal Palace,Wolves,4,2,H,...,3,0,71.428571,25.000000,2,-2,0.714286,0.250000,2.357143,1.125000
12150,2024-2025_Man City_Bournemouth,2024-2025,25,2025-05-20,20:00:00,Man City,Bournemouth,3,1,H,...,3,0,41.666667,25.000000,2,-2,0.416667,0.250000,1.708333,0.625000

In [36]:
# Save the DataFrame to a new CSV file
df.to_csv('EPL_cleaned_partial_explored_data.csv', index=False)